#!/usr/bin/env php
<?php

require __DIR__ . '/${VENDOR_DIR}/autoload.php';

use PHPComposter\PHPComposter\GeneralHook;
$generalHook = new GeneralHook($argv);
$generalHook->run($argv, __DIR__ . '/${VENDOR_DIR}');